### ISSUE TITLE
Invalid Notation error for decimal inputs

### ISSUE THREAD

**Issue by tomarney** [asmpro7/StatisFlow#1]
Nice idea for this plugin and thanks for making it!

Does it support statistics for decimal values? I get the "Invalid Notation" error message if I try and use decimals, but it works with integers.

I think for this to be useful it should allow decimal values.

**Comment by asmpro7** [comment]
Oh ,thx to tell me I will work on it soon and make it support 
I'm happy to see someone use my statis plugin 
if you have any other idea to add to it like some tests and other summary statistics I will be happy to add them to it

**Comment by asmpro7** [comment]
It should now  support decimal values in v1.1.0
update it and enjoy !
